import React from 'react';
import { Navigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowUpRight, BrainCircuit, CalendarDays, Clock3, Sparkles, TrendingUp, TriangleAlert } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import AppShell from '../components/AppShell.jsx';

const insights = [
  ['Timing pattern', 'You struggle after 9 PM.', 'Move difficult graph recalls into your 7:30 PM focus window.', Clock3, 'amber'],
  ['Memory signal', 'Arrays retention increased 17%.', 'Your last three spaced reviews landed in the durable-memory range.', TrendingUp, 'mint'],
  ['Watch list', 'Dynamic Programming is getting weaker.', 'Two items are moving into the 48-hour forgetting window.', TriangleAlert, 'rose'],
];
export default function Insights() { const { user, loading } = useAuth(); if (loading) return <div className="app-loading"><BrainCircuit /></div>; if (!user) return <Navigate to="/login" replace />; return <AppShell active="insights"><main className="insights-page"><section className="topbar"><div><p className="eyebrow">PERSONAL INTELLIGENCE</p><h1>Your learning, <span>made visible.</span></h1><p className="page-intro">Signals from 72 recall attempts, turned into a calmer plan for what to do next.</p></div><button className="outline-button"><CalendarDays size={16} /> Last 30 days</button></section><motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="readiness-card"><div className="readiness-orb"><span>82</span><small>%</small></div><div><p className="eyebrow">INTERVIEW READINESS</p><h2>You're closer than you think.</h2><p>Your foundations are consistent. Strengthen Graphs and Dynamic Programming to unlock a more reliable interview baseline.</p></div><div className="readiness-actions"><span>Next milestone</span><b>Gold league</b><button>See path <ArrowUpRight size={15} /></button></div></motion.section><section className="insight-grid">{insights.map(([label, title, copy, Icon, color], i) => <motion.article initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 + i * .08 }} key={label} className="insight-card"><span className={`insight-icon ${color}`}><Icon size={20} /></span><p className="eyebrow">{label}</p><h2>{title}</h2><p>{copy}</p><button>Act on insight <ArrowUpRight size={14} /></button></motion.article>)}</section><section className="surface coach-plan"><div className="coach-icon"><Sparkles size={19} /></div><div><p className="eyebrow">TOMORROW'S COACH PLAN</p><h2>Revise Dijkstra before 10 AM.</h2><p>It has the highest expected recall gain of anything in your queue: +14% confidence from 16 focused minutes.</p></div><button className="start-button">Add to focus</button></section></main></AppShell>; }
